### ISSUE TITLE
mDesktop and pnotes.net stickies

### ISSUE THREAD

**Issue by tickseeker** [octalmage/mDesktop#25] opened 2014-12-14 08:12 UTC
https://sourceforge.net/projects/pnotes/ application sticky notes does not work right on mDesktop.exe

I do not know which one is the problem, but when I create a new sticky note (window) it does not stay on that desktop where I created it. For some reason it is occasionally copied to some other desktops too. This is continuous habit.

**Comment by octalmage** [comment] 2015-02-04 23:45
I'll have to test to confirm, but mDesktop works by showing/hiding windows. So if an application shows a window on it's own, it messes with mDesktop. mDesktop creates a list of windows on switching, so if the window is visible on desktop 1, then the app unhides itself on desktop 2, mDesktop stores the window on both desktops. Currently I don't know of a way around this without adding a bunch of overhead. 

Do you know the steps to reproduce this?

**Comment by tickseeker** [comment] 2015-02-05 03:19
I understand. 

It happens continuously by the way I cannot understand... I switched to Microsoft's Stickies and works just fine :)

**Comment by octalmage** [comment] 2015-02-06 17:53
Well that works!!

**Comment by octalmage** [comment] 2015-08-13 21:06
I'm going to close this since it's not really an issue I can fix.

**Closed by octalmage** 2015-08-13 21:06 UTC
